name: Automation

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint with pylint
      run: sudo apt-get install pylint
    - name: Test API
      run: pwd && ls && cd .. && ls
